
-- Добавляем тестовые картины с полными данными на трех языках
INSERT INTO paintings (
  id,
  owner_id,
  title_en,
  title_fr,
  title_ru,
  artist_en,
  artist_fr,
  artist_ru,
  description_en,
  description_fr,
  description_ru,
  technical_analysis_en,
  technical_analysis_fr,
  technical_analysis_ru,
  expertise_report_en,
  expertise_report_fr,
  expertise_report_ru,
  year,
  public_image_url,
  is_published,
  certificates,
  documents
) VALUES 
(
  gen_random_uuid(),
  (SELECT id FROM auth.users LIMIT 1), -- Используем первого доступного пользователя
  'The Starry Night Over the Rhône',
  'La Nuit étoilée sur le Rhône',
  'Звёздная ночь над Роной',
  'Vincent van Gogh',
  'Vincent van Gogh',
  'Винсент ван Гог',
  'A masterpiece painted in 1888, depicting the night sky over the Rhône River in Arles. Van Gogh''s distinctive brushstrokes capture the reflection of stars and artificial light on the water.',
  'Un chef-d''œuvre peint en 1888, représentant le ciel nocturne au-dessus du Rhône à Arles. Les coups de pinceau distinctifs de Van Gogh capturent le reflet des étoiles et de la lumière artificielle sur l''eau.',
  'Шедевр, написанный в 1888 году, изображающий ночное небо над рекой Рона в Арле. Характерные мазки Ван Гога передают отражение звёзд и искусственного света на воде.',
  'Oil on canvas, 72.5 cm × 92 cm. The painting demonstrates Van Gogh''s innovative technique of thick paint application (impasto) and bold color choices. Analysis reveals ultramarine blue and cadmium yellow pigments typical of the period.',
  'Huile sur toile, 72,5 cm × 92 cm. La peinture démontre la technique innovante de Van Gogh d''application de peinture épaisse (impasto) et ses choix de couleurs audacieux. L''analyse révèle des pigments bleu outremer et jaune de cadmium typiques de l''époque.',
  'Масло на холсте, 72,5 см × 92 см. Картина демонстрирует новаторскую технику Ван Гога нанесения густой краски (импасто) и смелый выбор цветов. Анализ выявляет ультрамариновую синюю и кадмиевую жёлтую краски, типичные для того периода.',
  'Authenticated by the Van Gogh Museum. This work has been extensively studied and verified through X-ray analysis, pigment testing, and provenance research. Certificate of authenticity issued by leading art historians.',
  'Authentifié par le Musée Van Gogh. Cette œuvre a été largement étudiée et vérifiée par analyse aux rayons X, tests de pigments et recherche de provenance. Certificat d''authenticité délivré par des historiens d''art de premier plan.',
  'Аутентифицирована Музеем Ван Гога. Произведение было тщательно изучено и проверено с помощью рентгеновского анализа, тестирования пигментов и исследования происхождения. Сертификат подлинности выдан ведущими искусствоведами.',
  1888,
  'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Starry_Night_Over_the_Rhone.jpg/800px-Starry_Night_Over_the_Rhone.jpg',
  true,
  '[{"name": "Certificate of Authenticity", "type": "authentication", "issuer": "Van Gogh Museum", "date": "2023", "url": "#"}, {"name": "Insurance Appraisal", "type": "valuation", "issuer": "Sotheby''s", "date": "2024", "url": "#"}]'::jsonb,
  '[{"name": "X-Ray Analysis Report", "type": "technical", "date": "2023", "url": "#"}, {"name": "Pigment Analysis", "type": "scientific", "date": "2023", "url": "#"}]'::jsonb
),
(
  gen_random_uuid(),
  (SELECT id FROM auth.users LIMIT 1),
  'Water Lilies',
  'Les Nymphéas',
  'Кувшинки',
  'Claude Monet',
  'Claude Monet',
  'Клод Моне',
  'Part of Monet''s famous series painted in his garden at Giverny. This impressionist masterpiece captures the play of light on water through loose brushstrokes and vibrant colors.',
  'Partie de la célèbre série de Monet peinte dans son jardin à Giverny. Ce chef-d''œuvre impressionniste capture le jeu de la lumière sur l''eau à travers des coups de pinceau libres et des couleurs vibrantes.',
  'Часть знаменитой серии Моне, написанной в его саду в Живерни. Этот импрессионистский шедевр передаёт игру света на воде свободными мазками и яркими красками.',
  'Oil on canvas, 200 cm × 300 cm. The work showcases Monet''s mature impressionist technique with visible brushstrokes and color mixing directly on canvas. Scientific analysis confirms the use of modern synthetic pigments.',
  'Huile sur toile, 200 cm × 300 cm. L''œuvre présente la technique impressionniste mature de Monet avec des coups de pinceau visibles et un mélange de couleurs directement sur la toile. L''analyse scientifique confirme l''utilisation de pigments synthétiques modernes.',
  'Масло на холсте, 200 см × 300 см. Работа демонстрирует зрелую импрессионистскую технику Моне с видимыми мазками и смешением красок прямо на холсте. Научный анализ подтверждает использование современных синтетических пигментов.',
  'Verified through comparative analysis with other works in the series. Provenance traced back to the artist''s estate. Multiple expert opinions confirm attribution to Monet.',
  'Vérifié par analyse comparative avec d''autres œuvres de la série. Provenance retracée jusqu''à la succession de l''artiste. Plusieurs avis d''experts confirment l''attribution à Monet.',
  'Проверена через сравнительный анализ с другими работами серии. Происхождение прослежено до наследия художника. Множественные экспертные заключения подтверждают авторство Моне.',
  1919,
  'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Claude_Monet_-_Water_Lilies_-_1919%2C_Metropolitan_Museum_of_Art.jpg/800px-Claude_Monet_-_Water_Lilies_-_1919%2C_Metropolitan_Museum_of_Art.jpg',
  true,
  '[{"name": "Museum Authentication", "type": "authentication", "issuer": "Metropolitan Museum", "date": "2022", "url": "#"}]'::jsonb,
  '[{"name": "Conservation Report", "type": "condition", "date": "2022", "url": "#"}]'::jsonb
),
(
  gen_random_uuid(),
  (SELECT id FROM auth.users LIMIT 1),
  'Girl with a Pearl Earring',
  'La Jeune Fille à la perle',
  'Девушка с жемчужной серёжкой',
  'Johannes Vermeer',
  'Johannes Vermeer',
  'Йоханнес Вермеер',
  'One of Vermeer''s most famous works, painted around 1665. The mysterious subject gazes over her shoulder with an enigmatic expression, wearing an exotic turban and a large pearl earring.',
  'L''une des œuvres les plus célèbres de Vermeer, peinte vers 1665. Le sujet mystérieux regarde par-dessus son épaule avec une expression énigmatique, portant un turban exotique et une grande boucle d''oreille en perle.',
  'Одна из самых знаменитых работ Вермеера, написанная около 1665 года. Загадочная модель смотрит через плечо с загадочным выражением, в экзотическом тюрбане и с большой жемчужной серёжкой.',
  'Oil on canvas, 44.5 cm × 39 cm. Vermeer''s signature use of ultramarine blue and masterful handling of light. The pearl is painted with remarkable luminosity using lead white and subtle glazes.',
  'Huile sur toile, 44,5 cm × 39 cm. L''utilisation caractéristique de Vermeer du bleu outremer et sa maîtrise de la lumière. La perle est peinte avec une luminosité remarquable utilisant du blanc de plomb et des glacis subtils.',
  'Масло на холсте, 44,5 см × 39 см. Характерное использование Вермеером ультрамаринового синего и мастерское обращение со светом. Жемчужина написана с замечательной светимостью с использованием свинцовых белил и тонких лессировок.',
  'Extensive research confirms attribution to Vermeer. Technical analysis reveals painting techniques consistent with the artist''s documented methods. Dendrochronological analysis of the wood panel supports 17th-century dating.',
  'Des recherches approfondies confirment l''attribution à Vermeer. L''analyse technique révèle des techniques de peinture cohérentes avec les méthodes documentées de l''artiste. L''analyse dendrochronologique du panneau de bois soutient une datation du XVIIe siècle.',
  'Обширные исследования подтверждают авторство Вермеера. Технический анализ выявляет живописные техники, соответствующие документированным методам художника. Дендрохронологический анализ деревянной панели поддерживает датировку XVII веком.',
  1665,
  'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/1665_Girl_with_a_Pearl_Earring.jpg/800px-1665_Girl_with_a_Pearl_Earring.jpg',
  true,
  '[{"name": "Mauritshuis Authentication", "type": "authentication", "issuer": "Mauritshuis Museum", "date": "2021", "url": "#"}]'::jsonb,
  '[{"name": "Technical Analysis Report", "type": "technical", "date": "2021", "url": "#"}]'::jsonb
),
(
  gen_random_uuid(),
  (SELECT id FROM auth.users LIMIT 1),
  'The Persistence of Memory',
  'La Persistance de la mémoire',
  'Постоянство памяти',
  'Salvador Dalí',
  'Salvador Dalí',
  'Сальвадор Дали',
  'Dalí''s surrealist masterpiece from 1931, featuring the famous melting clocks. The painting explores concepts of time, memory, and the subconscious mind through dreamlike imagery.',
  'Le chef-d''œuvre surréaliste de Dalí de 1931, mettant en vedette les célèbres horloges qui fondent. La peinture explore les concepts de temps, de mémoire et de l''esprit subconscient à travers des images oniriques.',
  'Сюрреалистический шедевр Дали 1931 года с знаменитыми тающими часами. Картина исследует концепции времени, памяти и подсознания через сновидческие образы.',
  'Oil on canvas, 24 cm × 33 cm. Dalí''s meticulous technique combines photographic realism with surreal elements. The painting demonstrates his "paranoiac-critical method" of accessing the subconscious.',
  'Huile sur toile, 24 cm × 33 cm. La technique méticuleuse de Dalí combine le réalisme photographique avec des éléments surréels. La peinture démontre sa "méthode paranoïaque-critique" d''accès au subconscient.',
  'Масло на холсте, 24 см × 33 см. Скрупулёзная техника Дали сочетает фотографический реализм с сюрреальными элементами. Картина демонстрирует его "параноидально-критический метод" доступа к подсознанию.',
  'Authenticated by the Dalí Foundation. The work''s provenance is well-documented from the artist''s studio to its current location. Multiple scholarly publications confirm its authenticity.',
  'Authentifié par la Fondation Dalí. La provenance de l''œuvre est bien documentée depuis l''atelier de l''artiste jusqu''à son emplacement actuel. Plusieurs publications savantes confirment son authenticité.',
  'Аутентифицирован Фондом Дали. Происхождение работы хорошо документировано от мастерской художника до её нынешнего местонахождения. Множественные научные публикации подтверждают её подлинность.',
  1931,
  'https://upload.wikimedia.org/wikipedia/en/thumb/d/dd/The_Persistence_of_Memory.jpg/800px-The_Persistence_of_Memory.jpg',
  true,
  '[{"name": "Dalí Foundation Certificate", "type": "authentication", "issuer": "Gala-Salvador Dalí Foundation", "date": "2020", "url": "#"}]'::jsonb,
  '[{"name": "Scholarly Catalog", "type": "academic", "date": "2020", "url": "#"}]'::jsonb
),
(
  gen_random_uuid(),
  (SELECT id FROM auth.users LIMIT 1),
  'The Great Wave off Kanagawa',
  'La Grande Vague de Kanagawa',
  'Большая волна в Канагаве',
  'Katsushika Hokusai',
  'Katsushika Hokusai',
  'Кацусика Хокусай',
  'The most famous woodblock print from Hokusai''s series "Thirty-six Views of Mount Fuji". Created around 1831, it depicts a giant wave threatening boats with Mount Fuji visible in the background.',
  'La plus célèbre estampe de la série de Hokusai "Trente-six vues du mont Fuji". Créée vers 1831, elle représente une vague géante menaçant des bateaux avec le mont Fuji visible en arrière-plan.',
  'Самая знаменитая гравюра на дереве из серии Хокусая "Тридцать шесть видов горы Фудзи". Созданная около 1831 года, она изображает гигантскую волну, угрожающую лодкам, с горой Фудзи на заднем плане.',
  'Woodblock print (nishiki-e), 25.7 cm × 37.9 cm. The print uses Prussian blue (newly imported to Japan) and demonstrates Hokusai''s mastery of perspective and dynamic composition.',
  'Estampe sur bois (nishiki-e), 25,7 cm × 37,9 cm. L''estampe utilise le bleu de Prusse (nouvellement importé au Japon) et démontre la maîtrise de Hokusai de la perspective et de la composition dynamique.',
  'Ксилография (нишики-э), 25,7 см × 37,9 см. Гравюра использует прусскую синь (недавно импортированную в Японию) и демонстрирует мастерство Хокусая в перспективе и динамичной композиции.',
  'This impression shows excellent color preservation and clear registration of all blocks. Watermark analysis confirms 19th-century Japanese paper. Expert evaluation by ukiyo-e specialists.',
  'Cette impression montre une excellente préservation des couleurs et un repérage clair de tous les blocs. L''analyse du filigrane confirme le papier japonais du XIXe siècle. Évaluation d''experts par des spécialistes d''ukiyo-e.',
  'Этот оттиск показывает отличную сохранность цветов и чёткую приводку всех досок. Анализ водяных знаков подтверждает японскую бумагу XIX века. Экспертная оценка специалистами укиё-э.',
  1831,
  'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/The_Great_Wave_off_Kanagawa.jpg/800px-The_Great_Wave_off_Kanagawa.jpg',
  true,
  '[{"name": "Ukiyo-e Expert Certificate", "type": "authentication", "issuer": "Japanese Art Society", "date": "2023", "url": "#"}]'::jsonb,
  '[{"name": "Paper Analysis Report", "type": "technical", "date": "2023", "url": "#"}]'::jsonb
);
